### ISSUE TITLE
Configuration service

### ISSUE THREAD

**Issue by ebakoba** [ebakoba/automatic-air-conditioner#1]
Configuration service should be able to read in `config.json` and serve values contained there to rest of the program.

Example of `config.json`, where  threshold is on switch temperature in Celsius and is switch 
so called cooldown period in minutes

```json
{
  "threshold": 24,
  "cooldown": 60
}
``` 

Usage of this service should look something like this
```python
from configuration import ConfigService

configService = ConfigService()

config = configService.getConfig()

threshold = config['threshold']
cooldown = config['cooldown']
```

One MUST HAVE aspect of the config service is that it must be live reloaded. Meaning that program must adapt changes is config without being restarted. Threads must be used for this, one option is to declare setInterval method like [this](https://stackoverflow.com/questions/2697039/python-equivalent-of-setinterval).

**Comment by mariak4s** [comment]
Configuration service **added** and **tested**.
