### ISSUE TITLE
RelayService

### ISSUE THREAD

**Issue by ebakoba** [ebakoba/automatic-air-conditioner#2]
This service should know in which state the relay currently is and also implement a function to switch to another state.

Implementation should look something like this:

```python
class RelayService:
    def __init__(self, pin):
        # implementation

    def get_state():
        # implementation

    def switch():
        # implementation
```

Usage
```python
relayService = RelayService(16)

current_state = relayService.get_state()
relayService.switch()
```

For the GPIO interaction [this library](https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/) should be used.

**Comment by mariak4s** [comment]
relayservice.py added, needs testing
